import type { Locale } from '@/i18n-config'

export const featuredProductSlugs = [
  'gla07512k-t2-itz1212ip-imaging-kit',
  'teledyne-flir-oem-boson',
  'guide-sensmart-pv400',
] as const

export const companyContent = {
  en: {
    title: 'Infrared Cameras, Customization & Supply',
    description: 'Cooyue Tech provides infrared camera customization, equipment sales and after-sales support for overseas customers. Email us to discuss your application.',
    heroTag: 'Infrared cameras · Customization · After-sales support',
    heroTitle: 'Infrared equipment for your next project',
    heroText: 'Looking for a camera, an imaging assembly or a gas imaging solution? Tell us what you need to see, measure or integrate. We help you clarify the options and the next steps.',
    browse: 'Explore products',
    inquire: 'Email your requirements',
    form: 'Send an inquiry',
    aboutTag: 'About Cooyue Tech',
    aboutTitle: 'A practical point of contact for infrared equipment',
    aboutText: 'Cooyue Tech is the international-facing brand of 杭州科越设备有限公司. We focus on infrared camera customization, equipment sales and after-sales support, helping overseas customers discuss product selection and project requirements in one place.',
    aboutMore: 'Get to know Cooyue Tech',
    servicesTag: 'How we help',
    servicesTitle: 'From a clear requirement to a confirmed order',
    services: [
      { title: 'Camera customization', text: 'Share your mounting space, interfaces and operating conditions. We review the customization scope with you before confirming a configuration.', icon: 'fa-cog' },
      { title: 'Equipment sales', text: 'Start with a model or an application. We discuss the equipment, quantity and destination, then confirm pricing and delivery terms by email.', icon: 'fa-camera' },
      { title: 'After-sales support', text: 'Keep your model, order details and a description of the issue ready. We help coordinate the next steps within the agreed support scope.', icon: 'fa-envelope' },
    ],
    featuredTag: 'Start with these products',
    featuredTitle: 'Imaging assemblies, infrared cores and gas imaging',
    featuredText: 'Explore three starting points for a purchasing or customization discussion. Configuration and delivery terms are confirmed with your inquiry.',
    featured: [
      { title: 'GLA07512K-T2 + ITZ1212IP', category: 'Imaging assembly', text: 'An open assembly with optics, an SDI imaging core and K10 Ethernet conversion. Explore its components before discussing platform integration.' },
      { title: 'Boson', category: 'Infrared core', text: 'An infrared core for a component-level selection discussion. Tell us your integration requirements so we can confirm the appropriate configuration.' },
      { title: 'PV400', category: 'Optical gas imaging', text: 'A starting point for gas imaging inquiries. Specify the target gas, inspection task and operating environment for a suitability review.' },
    ],
    detail: 'View product details',
    processTag: 'A useful first email',
    processTitle: 'No model selected yet? Start with the application.',
    processText: 'You do not need a complete specification to contact us. A clear description of the task is enough to begin the discussion.',
    steps: [
      { title: 'Describe the task', text: 'Tell us the target, viewing distance, installation location and what the equipment needs to do.' },
      { title: 'Share the constraints', text: 'Include interfaces, available space, environmental conditions and any documents you can share.' },
      { title: 'Confirm the next step', text: 'Add the quantity, destination country and preferred schedule. We can then discuss options and outstanding questions.' },
    ],
    contactTitle: 'Let’s discuss your infrared equipment requirements',
    contactText: 'Email is our primary contact channel for overseas inquiries. Include your application, model if known, quantity and destination country. We will use your email address to follow up.',
    contactNote: 'Pricing, configuration, lead time and after-sales terms are confirmed for each inquiry. No fixed delivery time or universal performance claim is implied by this website.',
    referenceTitle: 'Product information and brand references',
    referenceText: 'The catalog also includes third-party products for reference. Cooyue Tech has no partnership or authorized distributor relationship with the displayed brands. A listing is not a promise of supply; availability and any proposed equipment must be confirmed by email.',
    productNote: 'Specifications, availability, lead time and suitability are confirmed for each inquiry. Third-party brand listings are references only and do not imply a partnership or authorization.',
    locationLabel: 'Company location',
    location: 'Hangzhou, China',
    phone: 'Phone',
    email: 'Email inquiries',
    legalName: 'Company: 杭州科越设备有限公司 · International brand: Cooyue Tech',
    formName: 'Your name',
    formEmail: 'Your work email',
    formMessage: 'Application, model, quantity, destination and questions to confirm',
    guidesTitle: 'Practical guides for your next inquiry',
    guidesDescription: 'Prepare an infrared camera inquiry, define customization requirements and discuss gas imaging or after-sales support with Cooyue Tech.',
    guidesIntro: 'Short checklists to help you describe your requirements clearly. These guides support a discussion; they are not product specifications or operating instructions.',
    faqTitle: 'Products, customization and purchasing: your questions',
    faqDescription: 'Answers about infrared camera inquiries, customization, reference products, quotations and after-sales support at Cooyue Tech.',
    careersTitle: 'Work with Cooyue Tech',
    careersText: 'We have not published current vacancies on this website. For work or project cooperation inquiries, email a brief introduction and the area you would like to discuss. Recruitment terms, if any, will be confirmed directly.',
  },
  zh: {
    title: '红外摄像头定制、销售与售后支持',
    description: '杭州科越设备有限公司（Cooyue Tech）面向海外客户提供红外摄像头定制、设备销售与售后支持。欢迎通过邮箱咨询红外设备、气体成像和项目方案。',
    heroTag: '红外摄像头 · 设备定制 · 售后支持',
    heroTitle: '为你的项目，找到合适的红外设备',
    heroText: '需要红外摄像头、成像组件或气体红外成像方案？告诉我们你希望观察、测量或集成的任务，一起把产品方向和下一步要求确认清楚。',
    browse: '浏览产品',
    inquire: '邮件咨询需求',
    form: '发送询盘',
    aboutTag: '关于 Cooyue Tech',
    aboutTitle: '以务实沟通，推进红外设备选型与采购',
    aboutText: '杭州科越设备有限公司以 Cooyue Tech 面向海外客户开展业务，专注红外摄像头的定制、设备销售与售后支持。无论你已有明确型号，还是正在寻找项目方向，都可以与我们讨论产品选择和实际要求。',
    aboutMore: '了解科越',
    servicesTag: '我们提供什么',
    servicesTitle: '从明确需求，到确认采购方案',
    services: [
      { title: '摄像头定制', text: '说明安装空间、接口和工作环境。我们与你核对定制范围，再确认具体配置，不以通用方案替代项目要求。', icon: 'fa-cog' },
      { title: '设备销售', text: '可以从型号开始，也可以从应用出发。结合设备、数量和目的地，通过邮件确认报价与交付条件。', icon: 'fa-camera' },
      { title: '售后支持', text: '提供型号、订单信息及问题描述。我们根据约定的支持范围，协助沟通后续处理步骤。', icon: 'fa-envelope' },
    ],
    featuredTag: '重点产品',
    featuredTitle: '从成像组件、红外机芯与气体成像开始',
    featuredText: '三个可用于采购或定制沟通的产品方向。具体配置与交付条件随询盘确认。',
    featured: [
      { title: 'GLA07512K-T2 + ITZ1212IP', category: '成像组件套件', text: '由镜头、SDI 机芯与 K10 以太网转换等组件组成的开放式套件。先了解组件关系，再讨论平台集成要求。' },
      { title: 'Boson', category: '红外机芯', text: '面向组件级选型讨论的红外机芯。告诉我们集成要求，进一步确认适用配置。' },
      { title: 'PV400', category: '气体红外成像', text: '气体红外成像询盘的产品方向。请说明目标气体、巡检任务与使用环境，以便核对适用条件。' },
    ],
    detail: '查看产品详情',
    processTag: '如何开始沟通',
    processTitle: '还没选定型号？先说清楚应用。',
    processText: '不必等到所有参数齐全才联系我们。对任务的清晰描述，就是有效沟通的开始。',
    steps: [
      { title: '描述任务', text: '说明观察目标、使用距离、安装位置，以及希望设备完成的工作。' },
      { title: '补充限制', text: '提供接口、可用空间、环境条件，以及可以分享的图纸或需求文件。' },
      { title: '明确下一步', text: '补充数量、目的国家和期望时间，再一起讨论可选方向与待确认问题。' },
    ],
    contactTitle: '把红外设备需求，交给一次清晰的邮件沟通',
    contactText: '邮箱是我们面向海外客户的主要联系渠道。请提供应用、已知型号、数量和目的国家，我们会通过你留下的邮箱继续沟通。',
    contactNote: '价格、配置、交期和售后条款按具体询盘确认。本站不以统一交期或通用性能指标替代产品与项目核对。',
    referenceTitle: '产品资料与品牌说明',
    referenceText: '目录同时收录第三方产品供选型参考。Cooyue Tech 与所展示品牌不存在合作或授权代理关系；收录不代表供货承诺。实际可供设备、配置与适用条件需通过邮件确认。',
    productNote: '具体参数、供货情况、交期和适用条件按询盘确认。第三方品牌收录仅用于参考，不代表合作或授权代理关系。',
    locationLabel: '公司所在地',
    location: '中国 · 杭州',
    phone: '电话联系',
    email: '邮箱询盘',
    legalName: '杭州科越设备有限公司 · Cooyue Tech',
    formName: '你的姓名',
    formEmail: '联系邮箱',
    formMessage: '请说明应用、型号、数量、目的国家及待确认问题',
    guidesTitle: '让下一次询盘更清晰',
    guidesDescription: '了解如何准备红外摄像头询盘、梳理定制要求，以及与 Cooyue Tech 沟通气体成像选型和售后问题。',
    guidesIntro: '用简明清单整理采购和项目要求。这些内容帮助你开启沟通，不代替具体产品参数或操作说明。',
    faqTitle: '关于产品、定制与采购，你可能想了解',
    faqDescription: '了解 Cooyue Tech 红外摄像头询盘、定制沟通、参考产品、报价和售后支持的常见问题。',
    careersTitle: '与 Cooyue Tech 一起工作',
    careersText: '本站暂未公布在招职位。如有求职或项目协作意向，请通过邮箱简要介绍自己和希望沟通的方向。若涉及招聘，具体安排另行确认。',
  },
}

export function getCompanyContent(locale: Locale) {
  return companyContent[locale]
}
